# This is a basic workflow to help you get started with Actions

name: Deploy to Apigee X Prod

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell

      - name: Auth with Google
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          create_credentials_file: true
          activate_credentials_file: true
          project_id: ${{ secrets.APIGEE_ORG }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_POOL_ID }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Create API bundle
        run: zip -r proxy.zip apiproxy
      - name: Upload API Proxy Bundle
        id: upload
        run: "echo \"apigee-revision=$(curl --fail -X POST -H \"Content-Type: multipart/form-data\" -H \"Authorization: Bearer ${{steps.auth.outputs.access_token}}\" -F \"file=@proxy.zip\" \"https://apigee.googleapis.com/v1/organizations/${{secrets.APIGEE_ORG}}/apis?action=import&name=hello-world-ga\" --silent | jq --raw-output .revision)\" >> $GITHUB_OUTPUT"
      - name: Deploy Revision to environment ${{ secrets.APIGEE_ENV }}
        id: deploy
        run: "curl \"https://apigee.googleapis.com/v1/organizations/${{ secrets.APIGEE_ORG }}/environments/${{ secrets.APIGEE_ENV }}/apis/hello-world-ga/revisions/${{steps.upload.outputs.apigee-revision}}/deployments?override=true\" -X POST -H \"Authorization: Bearer ${{steps.auth.outputs.access_token}}\" --silent | jq"
      - name: Checking API deployment
        id: check-deploy
        run: "echo \"deploy-status-get=$(curl \"https://apigee.googleapis.com/v1/organizations/${{ secrets.APIGEE_ORG }}/environments/${{ secrets.APIGEE_ENV }}/apis/hello-world-ga/revisions/${{steps.upload.outputs.apigee-revision}}/deployments\" -X GET -H \"Authorization: Bearer ${{steps.auth.outputs.access_token}}\" --silent | jq --raw-output .state)\" >> $GITHUB_OUTPUT"
      - name: Checking results
        run: "echo State: ${{steps.check-deploy.outputs.deploy-status-get}}"

